version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  prisma:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: npx prisma migrate dev --name init_auth

